#!/usr/bin/perl
############################################################################
# Reverse an IPv6 address for generating PTR zones
# Does not properly handle :: at this time.  Simple, not right
############################################################################
use strict;
use Getopt::Std;
use Net::IP qw(:PROC);

our %opts;

sub parse_args {
    my %opts;
    getopts('hdi:',\%opts);
    return %opts;
}

####
# main
####
%opts=parse_args();
ip_is_ipv6($opts{i}) || die "Missing a valid IPv6 address\n";
print "Forward=",ip_expand_address($opts{i},6),"\n";
print "Backward=",ip_reverse ($opts{i}),"\n";
